version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  mysql:
    image: pkpudev/mariadb-yii2:1.0
    ports:
      - 33066:3306
    environment:
      - MYSQL_USER=institute
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=pkpu_core

  #pgsql:
  #  image: pkpudev/postgres-yii2
  #  environment:
  #    - POSTGRES_USER=project
  #    - POSTGRES_PASSWORD=password
  #    - POSTGRES_DB=project_core